# Dockerfile-server

# Use a specific Node.js version
FROM node:18-alpine

# Set working directory
WORKDIR /ostad-server

# Copy package.json and package-lock.json for caching
COPY OstadServer/package*.json ./

# Install dependencies, including nodemon for development
RUN npm install && npm install --save-dev nodemon

# Copy the rest of the application
COPY OstadServer/ .

# Expose the port
EXPOSE 5050

# Use nodemon for live reloading in development
CMD ["npx", "nodemon", "server.js"]

