name: OstadAPP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ostad
          MONGO_INITDB_ROOT_PASSWORD: ostad
        options: >-
          --health-cmd="echo 'db.stats().ok' | mongo localhost:27017/test --quiet"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mongo-express:
        image: mongo-express:latest
        ports:
          - 8081:8081
        env:
          ME_CONFIG_MONGODB_SERVER: mongo
          ME_CONFIG_MONGODB_ADMINUSERNAME: ostad
          ME_CONFIG_MONGODB_ADMINPASSWORD: ostad
          ME_CONFIG_MONGODB_URI: mongodb://ostad:ostad@mongo:27017/
        options: --link mongo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ostad-server Docker Image
        run: |
          docker build -f Dockerfile-server -t ostad-server .

      - name: Build ostad-ui Docker Image
        run: |
          docker build -f Dockerfile-UI -t ostad-ui .

      - name: Run ostad-server Container
        run: |
          docker network create mongo_network
          docker run -d \
            --name ostad-server \
            --network mongo_network \
            -e MONGO_URI=mongodb://ostad:ostad@mongo:27017/ostad \
            -e MONGO_USERNAME=ostad \
            -e MONGO_PASSWORD=ostad \
            -p 5050:5050 \
            ostad-server

      - name: Run ostad-ui Container
        run: |
          docker run -d \
            --name ostad-ui \
            --network mongo_network \
            -p 5173:5173 \
            ostad-ui

      - name: Verify Containers Are Running
        run: docker ps -a
